# Generated by Django 2.2.13 on 2021-03-16 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viral', '0080_userguest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=40, null=True, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('passcode', models.CharField(blank=True, max_length=20, null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('companies', models.ManyToManyField(blank=True, to='viral.Company')),
                ('invited_guests', models.ManyToManyField(blank=True, to='viral.UserGuest')),
                ('invited_users', models.ManyToManyField(blank=True, to='viral.UserProfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_company_list', to='viral.UserProfile')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
