# Generated by Django 2.2.13 on 2021-03-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylist',
            name='previous_passcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
