# Generated by Django 2.2.13 on 2021-03-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_lists', '0002_companylist_previous_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylist',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
