# Generated by Django 2.2.28 on 2022-10-11 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0085_auto_20221011_1205'),
        ('company_lists', '0003_auto_20210323_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylist',
            name='affiliate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viral.Affiliate'),
        ),
        migrations.AddField(
            model_name='companylist',
            name='company_list_type',
            field=models.SmallIntegerField(choices=[(0, 'Static'), (1, 'Affiliate Submissions')], default=0),
        ),
        migrations.AlterField(
            model_name='companylist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_company_list', to='viral.UserProfile'),
        ),
    ]
