# Generated by Django 2.2.28 on 2022-10-11 12:10

from django.db import migrations
from shared.models.unique_uid import random_uid


def migrate(apps, schema_editor):
    ENTREPRENEUR = 0
    COMPANY_LIST_TYPE_AFFILIATE_SUBMISSIONS = 1
    affiliate_model = apps.get_model('viral', 'Affiliate')
    company_list_model = apps.get_model('company_lists', 'CompanyList')
    affiliate_program_entry_model = apps.get_model('viral', 'AffiliateProgramEntry')
    affiliate_program_supporter_submission = apps.get_model('viral', 'AffiliateProgramSupporterSubmission')

    for affiliate in affiliate_model.objects.all():

        uid = random_uid()
        while company_list_model.objects.filter(uid=uid).exists():
            uid = random_uid()

        company_list = company_list_model.objects.create(
            uid=uid,
            title=affiliate.name,
            description=f'Companies appear in this list if they submitted {affiliate.name}.',
            company_list_type=COMPANY_LIST_TYPE_AFFILIATE_SUBMISSIONS,
            affiliate=affiliate)

        if affiliate.flow_target == ENTREPRENEUR:
            company_ids = affiliate_program_entry_model.objects.filter(
                affiliate=affiliate,
            ).values_list('user_profile__company', flat=True)
        else:
            company_ids = affiliate_program_supporter_submission.objects.filter(
                affiliate=affiliate,
                supporter__user_profile__isnull=False
            ).values_list('supporter__user_profile__company', flat=True)

        if company_ids:
            company_list.companies.set(company_ids)


def revert(apps, schema_editor):
    COMPANY_LIST_TYPE_AFFILIATE_SUBMISSIONS = 1
    company_list_model = apps.get_model('company_lists', 'CompanyList')
    company_list_model.objects.filter(
        company_list_type=COMPANY_LIST_TYPE_AFFILIATE_SUBMISSIONS, affiliate__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('company_lists', '0004_add_list_type_affiliates_to_companylists'),
    ]

    operations = [
        migrations.RunPython(code=migrate, reverse_code=revert)
    ]
