# Generated by Django 2.2.28 on 2022-10-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_lists', '0005_create_affiliate_submissions_companylists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companylist',
            options={},
        ),
        migrations.AddConstraint(
            model_name='companylist',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('company_list_type', 0), ('owner__isnull', False)), models.Q(('affiliate__isnull', False), ('company_list_type', 1)), _connector='OR'), name='enforce_owner_or_affiliate'),
        ),
    ]
