# Generated by Django 2.2.27 on 2023-07-20 04:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0091_adjust_affiliate_landing_page_fields'),
        ('company_lists', '0006_add_companylist_check_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viral.Company')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'processes',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_lists.Process')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('company_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_lists.CompanyList')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='company_lists',
            field=models.ManyToManyField(through='company_lists.ProcessStep', to='company_lists.CompanyList'),
        ),
        migrations.AddConstraint(
            model_name='processstep',
            constraint=models.UniqueConstraint(fields=('process', 'company_list'), name='unique_process_step'),
        ),
    ]
