# Generated by Django 2.2.27 on 2023-08-07 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_lists', '0007_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='company_lists.Process'),
        ),
    ]
