# Generated by Django 2.2.27 on 2025-11-13 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_lists', '0008_process_steps_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylist',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viral.Affiliate'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='company_list',
            field=models.ForeignKey(blank=True, help_text='Leave this field empty to automatically create a new list', on_delete=django.db.models.deletion.CASCADE, to='company_lists.CompanyList'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
