# Generated by Django 2.2.13 on 2020-07-24 06:10

from django.db import migrations, models
import profiles.models.profile_id_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileIDField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=200, validators=[profiles.models.profile_id_field.validate_source])),
                ('user_profile_relation', models.CharField(blank=True, editable=False, max_length=100)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
