# Generated by Django 2.2.28 on 2025-12-09 07:37

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import shared.validators
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0068_remove_question_instructions_max_length'),
        ('viral', '0097_auto_20251119_0100'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_lists', '0009_auto_20251113_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='SdgRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('impact_rating', models.FloatField()),
                ('impact_score', models.IntegerField()),
                ('impact_negative', models.IntegerField()),
                ('impact_positive', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viral.Company')),
                ('company_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company_lists.CompanyList')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SdgImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sdg_target', models.FloatField()),
                ('impact_net', models.IntegerField()),
                ('impact_negative', models.IntegerField()),
                ('impact_positive', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viral.Company')),
                ('company_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company_lists.CompanyList')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SDGAffiliateProgramEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=40, null=True, unique=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdgaffiliateprogramentry_affiliate', to='viral.Affiliate')),
                ('responses', models.ManyToManyField(blank=True, related_name='sdgaffiliateprogramentry_responses', to='matching.Response')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdgaffiliateprogramentry_user_profile', to='viral.UserProfile')),
            ],
            options={
                'verbose_name': 'Affiliate Program - Entrepreneur submission',
                'verbose_name_plural': 'Affiliate Program - Entrepreneur submissions',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON object specifying the value: { "text": "" } or { "value": 1 } or { "min": 5, "max": 9 }', null=True, validators=[shared.validators.JSONSchemaValidator(limit_value={'oneOf': [{'required': ['text']}, {'required': ['value']}, {'required': ['date']}, {'required': ['min', 'max']}], 'properties': {'date': {'type': 'string'}, 'max': {'type': 'number'}, 'min': {'type': 'number'}, 'text': {'maxLength': 1500, 'type': 'string'}, 'value': {'type': 'number'}}, 'type': 'object'})])),
                ('answers', models.ManyToManyField(blank=True, help_text='Chosen Answers IDs', related_name='response_answers', to='matching.Answer')),
                ('question', models.ForeignKey(help_text='Question ID', on_delete=django.db.models.deletion.CASCADE, related_name='response_question', to='matching.Question')),
                ('user_profile', models.ForeignKey(help_text='User Profile ID', on_delete=django.db.models.deletion.CASCADE, related_name='response_user_profile', to='viral.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalResponse',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON object specifying the value: { "text": "" } or { "value": 1 } or { "min": 5, "max": 9 }', null=True, validators=[shared.validators.JSONSchemaValidator(limit_value={'oneOf': [{'required': ['text']}, {'required': ['value']}, {'required': ['date']}, {'required': ['min', 'max']}], 'properties': {'date': {'type': 'string'}, 'max': {'type': 'number'}, 'min': {'type': 'number'}, 'text': {'maxLength': 1500, 'type': 'string'}, 'value': {'type': 'number'}}, 'type': 'object'})])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(blank=True, db_constraint=False, help_text='Question ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='matching.Question')),
            ],
            options={
                'verbose_name': 'historical response',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
