# Generated by Django 2.2.28 on 2025-12-17 06:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import shared.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sdg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalresponse',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON object specifying the value: { "text": "" } or { "value": 1 } or { "min": 5, "max": 9 }', null=True, validators=[shared.validators.JSONSchemaValidator(limit_value={'additionalProperties': True, 'properties': {'date': {'type': 'string'}, 'max': {'type': 'number'}, 'min': {'type': 'number'}, 'text': {'maxLength': 1500, 'type': 'string'}, 'value': {'type': 'number'}}, 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='response',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON object specifying the value: { "text": "" } or { "value": 1 } or { "min": 5, "max": 9 }', null=True, validators=[shared.validators.JSONSchemaValidator(limit_value={'additionalProperties': True, 'properties': {'date': {'type': 'string'}, 'max': {'type': 'number'}, 'min': {'type': 'number'}, 'text': {'maxLength': 1500, 'type': 'string'}, 'value': {'type': 'number'}}, 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='sdgaffiliateprogramentry',
            name='responses',
            field=models.ManyToManyField(blank=True, related_name='sdgaffiliateprogramentry_responses', to='sdg.Response'),
        ),
    ]
