# Generated by Django 2.2.28 on 2026-01-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdg', '0002_auto_20251217_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdgrating',
            name='impact_rating',
            field=models.CharField(max_length=255),
        ),
    ]
