# Generated by Django 2.2.28 on 2026-01-06 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0097_auto_20251119_0100'),
        ('sdg', '0002_auto_20251217_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='SdgReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_url', models.URLField(max_length=2048)),
                ('report_date', models.DateField()),
                ('report_type', models.CharField(max_length=255)),
                ('report_status', models.CharField(max_length=255)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='viral.Affiliate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viral.Company')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
