# Generated by Django 2.2.28 on 2026-01-06 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdg', '0003_sdgreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdgreport',
            name='job_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sdgreport',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viral.Company'),
        ),
    ]
