# Generated by Django 2.2.28 on 2026-01-06 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdg', '0004_auto_20260106_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdgreport',
            old_name='report_status',
            new_name='job_status',
        ),
    ]
