# Generated by Django 2.2.28 on 2026-01-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdg', '0005_auto_20260106_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdgreport',
            name='report_url',
        ),
        migrations.AddField(
            model_name='sdgreport',
            name='report_pdf_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='sdgreport',
            name='report_xlsx_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
