# Generated by Django 2.2.28 on 2026-01-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdg', '0006_auto_20260108_0206'),
        ('sdg', '0003_auto_20260107_0436'),
    ]

    operations = [
    ]
