# Generated by Django 2.0.8 on 2018-08-29 11:32

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import viral.models.company
import matching


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('shortcode', models.CharField(max_length=4)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('logo', models.URLField()),
                ('stylesheet', models.URLField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(null=True)),
                ('description', models.TextField(null=True)),
                ('website', models.URLField(null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('founded_date', models.DateTimeField(null=True)),
                ('investing_level_range', django.contrib.postgres.fields.ranges.IntegerRangeField(
                    null=True, validators=[matching.models.supporter.validate_level_range])),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formatted_address', models.CharField(max_length=512)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.BooleanField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=254)),
                ('position', models.CharField(max_length=254)),
                ('linkedin', models.URLField()),
                ('photo', models.URLField()),
                ('company', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='viral.Company')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.SmallIntegerField(choices=[
                 (0, 'Entrepreneur'), (1, 'Investor'), (2, 'Resource')])),
                ('photo', models.URLField(null=True)),
                ('company', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='viral.Company')),
                ('source', models.ForeignKey(blank=True, null=True,
                                             on_delete=django.db.models.deletion.DO_NOTHING, to='viral.Affiliate')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='relationship',
            name='creator',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name='user_creator', to='viral.UserProfile'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='entrepreneur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='user_entrepreneur', to='viral.UserProfile'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='investor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='user_investor', to='viral.UserProfile'),
        ),
        migrations.AddField(
            model_name='company',
            name='locations',
            field=models.ManyToManyField(to='viral.Location'),
        ),
        migrations.AddField(
            model_name='company',
            name='sectors',
            field=models.ManyToManyField(to='viral.Sector'),
        ),
    ]
