# Generated by Django 2.0.8 on 2018-08-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
