# Generated by Django 2.0.8 on 2018-08-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0002_auto_20180830_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='uuid',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
