# Generated by Django 2.0.8 on 2018-08-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0003_auto_20180830_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='group',
            field=models.CharField(max_length=100),
        ),
    ]
