# Generated by Django 2.0.8 on 2018-08-31 10:51

from django.db import migrations
import csv


def import_sectors(apps, schema_editor):
    Sector = apps.get_model('viral', 'Sector')
    Group = apps.get_model('viral', 'Group')
    with open('viral/seeds/sectors.csv') as f:
        reader = csv.reader(f)
        next(reader, None)  # Skip header
        for row in reader:
            group_names = row[2].split('|')
            groups = []
            for group_name in group_names:
                group, _ = Group.objects.get_or_create(name=group_name)
                groups.append(group)
            sector, _ = Sector.objects.get_or_create(name=row[1], uuid=row[0])
            for group in groups:
                sector.groups.add(group)


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0005_auto_20180831_1049'),
    ]

    operations = [
        migrations.RunPython(import_sectors)
    ]
