# Generated by Django 2.0.8 on 2018-08-31 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0006_import_sectors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='SectorGroup',
        ),
    ]
