# Generated by Django 2.0.8 on 2018-09-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0007_auto_20180831_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectorGroup',
            new_name='Group',
        ),
        migrations.AlterField(
            model_name='sector',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
