# Generated by Django 2.0.8 on 2018-09-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0008_auto_20180921_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliate',
            old_name='stylesheet',
            new_name='spreadsheet',
        ),
    ]
