# Generated by Django 2.0.8 on 2018-10-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0009_auto_20180927_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='spreadsheet',
            field=models.URLField(null=True),
        ),
    ]
