# Generated by Django 2.0.8 on 2018-10-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0010_auto_20181002_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='spreadsheet',
            field=models.URLField(blank=True),
        ),
    ]
