# Generated by Django 2.0.8 on 2018-10-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0011_auto_20181002_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='shortcode',
            field=models.CharField(max_length=6),
        ),
    ]
