# Generated by Django 2.0.8 on 2018-11-07 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0012_auto_20181008_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
    ]
