# Generated by Django 2.0.8 on 2018-11-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0013_remove_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(max_length=1048576, null=True, upload_to='documents/'),
        ),
    ]
