# Generated by Django 2.0.8 on 2018-11-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0014_auto_20181107_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='founded_date',
            field=models.DateField(null=True),
        ),
    ]
