# Generated by Django 2.0.8 on 2018-11-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0015_auto_20181107_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='description',
            new_name='about',
        ),
    ]
