# Generated by Django 2.0.8 on 2018-12-19 10:34

from django.db import migrations, models
import viral.models.company


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0016_auto_20181107_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(null=True, upload_to=viral.models.company.uuid_upload),
        ),
    ]
