# Generated by Django 2.0.8 on 2018-12-19 11:11

from django.db import migrations, models
import viral.validators


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0017_auto_20181219_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=200, null=True, validators=[
                                   viral.validators.NoSchemeURLValidator()]),
        ),
    ]
