# Generated by Django 2.0.8 on 2018-12-20 09:04

from django.db import migrations, models
import viral.models.company


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0018_auto_20181219_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(null=True, upload_to=viral.models.company.uuid_upload, validators=[viral.models.company.validate_file_extension]),
        ),
    ]
