# Generated by Django 2.0.10 on 2019-01-24 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0019_auto_20181220_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viral.Company'),
        ),
    ]
