# Generated by Django 2.0.10 on 2019-01-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0020_auto_20190124_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
