# Generated by Django 2.0.10 on 2019-01-31 12:26

from django.db import migrations, models

import requests


def get_location_attr(components, meta):
    for value in components:
        if value["types"].count(meta) > 0:
            return value["long_name"]

    return None


def fix_locations(apps, schema_editor):
    locations = apps.get_model('viral', 'Location').objects.all().only(
        'latitude', 'longitude', 'country')

    base = 'https://maps.googleapis.com/maps/api/geocode/json?'
    for location in locations:
        params = 'latlng={lat},{lng}&sensor={sen}&key={key}'.format(
            lat=location.latitude,
            lng=location.longitude,
            sen=False,
            key='AIzaSyAq1HB__RCHgh2KHt4MfsYhUPDqqocgQzo'
        )
        url = '{base}{params}'.format(base=base, params=params)
        response = requests.get(url)
        components = response.json()["results"][0]["address_components"]

        l_country = get_location_attr(components, "country")
        l_location = get_location_attr(
            components, "administrative_area_level_1")

        # Sometimes certain locations doesn't contains a administrative
        # area, so we need to get the locality
        if l_location == None:
            l_location = get_location_attr(components, "locality")

        location.country = l_country
        location.location = l_location if l_location != None else l_country
        location.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0021_auto_20190130_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(
            fix_locations, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="location", name="location", field=models.CharField(max_length=200)),
        migrations.AlterField(
            model_name="location", name="country", field=models.CharField(max_length=200)),
    ]
