# Generated by Django 2.0.8 on 2019-02-11 05:21

from django.db import migrations, models
import viral.models.company


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0023_auto_20190208_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cover',
            field=models.FileField(null=True, upload_to=viral.models.company.uuid_cover_upload, validators=[viral.models.company.validate_file_extension]),
        ),
    ]
