# Generated by Django 2.0.10 on 2019-02-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0024_company_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='investing_level_range',
        ),
    ]
