# Generated by Django 2.0.10 on 2019-02-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0025_remove_company_investing_level_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='crunchbase_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Entrepreneur'), (1, 'Supporter')]),
        ),
    ]
