# Generated by Django 2.0.8 on 2019-03-05 11:20

from django.db import migrations, models
from itertools import count


def populate_slugs(apps, schema_editor):
    Company = apps.get_model('viral', 'Company')
    companies = Company.objects.order_by('id').all()
    for company in companies:
        company.slug = initial = company.name.replace(' ', '').lower()

        for x in count(1):
            if not Company.objects.filter(slug=company.slug).exists():
                break
            company.slug = '%s-%d' % (initial, x)

        company.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0026_auto_20190225_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.CharField(
                default=None, max_length=150, null=True, unique=True),
        ),
        migrations.RunPython(populate_slugs)
        # TODO: Remove null
    ]
