# Generated by Django 2.0.8 on 2019-03-06 10:11

from django.db import migrations, models
from itertools import count


def populate_slugs(apps, schema_editor):
    Affiliate = apps.get_model('viral', 'Affiliate')
    affiliates = Affiliate.objects.order_by('id').all()
    for affiliate in affiliates:
        affiliate.slug = initial = affiliate.shortcode.replace(' ', '').lower()

        for x in count(1):
            if not Affiliate.objects.filter(slug=affiliate.slug).exists():
                break
            affiliate.slug = '%s%d' % (initial, x)

        affiliate.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0027_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='slug',
            field=models.CharField(
                default=None, max_length=12, null=True, unique=True),
        ),
        migrations.RunPython(populate_slugs)
    ]
