# Generated by Django 2.0.8 on 2019-03-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0028_affiliate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='shortcode',
            field=models.CharField(max_length=15),
        ),
    ]
