# Generated by Django 2.0.8 on 2019-03-13 07:17

from django.db import migrations, models
from os import urandom


def populate_hashes(apps, schema_editor):
    Company = apps.get_model('viral', 'Company')

    companies = Company.objects.order_by('id').all()

    for company in companies:
        company.access_hash = urandom(5).hex()
        company.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0029_auto_20190311_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='access_hash',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.RunPython(populate_hashes),
    ]
