# Generated by Django 2.0.8 on 2019-03-13 11:50

from django.db import migrations, models


def populate_types(apps, schema_editor):
    UserProfile = apps.get_model('viral', 'UserProfile')
    Company = apps.get_model('viral', 'Company')

    user_profiles = UserProfile.objects.order_by('id').all()

    for profile in user_profiles:
        company = Company.objects.get(pk=profile.company.id)
        company.type = profile.type
        company.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0030_company_access_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.SmallIntegerField(
                choices=[(0, 'Entrepreneur'), (1, 'Supporter')], default=0),
            preserve_default=False,
        ),
        migrations.RunPython(populate_types),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.SmallIntegerField(
                choices=[(0, 'Entrepreneur'), (1, 'Supporter')]),
        ),
    ]
