# Generated by Django 2.0.8 on 2019-03-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0031_auto_20190313_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='type',
        ),
    ]
