# Generated by Django 2.0.10 on 2019-04-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0032_remove_userprofile_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='location',
            name='continent',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
