# Generated by Django 2.0.8 on 2019-04-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0032_remove_userprofile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='slug',
            field=models.CharField(default=None, max_length=15, null=True, unique=True),
        ),
    ]
