# Generated by Django 2.0.10 on 2019-04-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0033_auto_20190412_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viral.Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Entrepreneur'), (1, 'Supporter'), (2, 'Partner')]),
        ),
    ]
