# Generated by Django 2.0.10 on 2019-04-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0033_auto_20190408_0900'),
        ('viral', '0034_auto_20190412_1212'),
    ]

    operations = [
    ]
