# Generated by Django 2.0.10 on 2019-04-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0035_merge_20190422_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.URLField(blank=True)),
                ('locations', models.ManyToManyField(blank=True, to='viral.Location')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
