# Generated by Django 2.0.10 on 2019-04-23 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0036_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viral.Network'),
        ),
    ]
