# Generated by Django 2.0.10 on 2019-05-13 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0037_userprofile_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='network',
        ),
        migrations.AddField(
            model_name='company',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viral.Network'),
        ),
    ]
