# Generated by Django 2.0.13 on 2019-05-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0038_auto_20190513_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='network',
        ),
        migrations.AddField(
            model_name='company',
            name='networks',
            field=models.ManyToManyField(to='viral.Network'),
        ),
    ]
