# Generated by Django 2.0.13 on 2019-05-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0039_auto_20190527_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='networks',
            field=models.ManyToManyField(blank=True, to='viral.Network'),
        ),
    ]
