# Generated by Django 2.0.13 on 2019-05-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0040_auto_20190528_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='viral.Sector'),
        ),
    ]
