# Generated by Django 2.0.10 on 2019-01-31 12:26

from django.db import migrations, models

import requests


def get_location_attr(components, meta):
    for value in components:
        if value["types"].count(meta) > 0:
            return value["long_name"]

    return None


def fix_locations(apps, schema_editor):
    locations = apps.get_model('viral', 'Location').objects.all().only(
        'latitude', 'longitude', 'country', 'region', 'city')

    base = 'https://maps.googleapis.com/maps/api/geocode/json?'
    for location in locations:
        if (location.latitude != 0 and location.latitude != 1 and location.latitude != 1111):
            params = 'latlng={lat},{lng}&sensor={sen}&key={key}'.format(
                lat=location.latitude,
                lng=location.longitude,
                sen=False,
                key='AIzaSyAq1HB__RCHgh2KHt4MfsYhUPDqqocgQzo'
            )
            url = '{base}{params}'.format(base=base, params=params)
            response = requests.get(url)
            components = response.json()["results"][0]["address_components"]

        l_country = get_location_attr(components, "country")
        l_region = get_location_attr(
            components, "administrative_area_level_1")
        l_city = get_location_attr(
            components, "locality"
        )

        location.country = l_country
        location.region = l_region if l_region != None else ''
        location.city = l_city if l_city != None else ''
        location.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0041_auto_20190529_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=200,  null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(blank=True, max_length=200,  null=True),
        ),
        migrations.RunPython(
            fix_locations, reverse_code=migrations.RunPython.noop),
    ]
