# Generated by Django 2.0.13 on 2019-06-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0043_admintokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admintokens',
            old_name='user_id',
            new_name='user',
        ),
    ]
