# Generated by Django 2.0.13 on 2019-06-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0044_auto_20190626_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintokens',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
