# Generated by Django 2.0.13 on 2019-08-19 10:18

from django.db import migrations, models

import requests


def get_location_attr(components, meta):
    for value in components:
        if value["types"].count(meta) > 0:
            return value["short_name"]

    return None


def populate_regions_abbreviations(apps, schema_editor):
    locations = apps.get_model('viral', 'Location').objects.all()

    base = 'https://maps.googleapis.com/maps/api/geocode/json?'
    for location in locations:
        hasValidCoordinates = location.latitude != 0 and location.latitude != 1 and location.latitude != 1111
        if (hasValidCoordinates and len(location.region)):
            params = 'latlng={lat},{lng}&sensor={sen}&key={key}'.format(
                lat=location.latitude,
                lng=location.longitude,
                sen=False,
                key='AIzaSyAq1HB__RCHgh2KHt4MfsYhUPDqqocgQzo'
            )
            url = '{base}{params}'.format(base=base, params=params)
            response = requests.get(url)
            components = response.json()["results"][0]["address_components"]

            region_abbreviation = get_location_attr(
                components, "administrative_area_level_1") or get_location_attr(
                components, "administrative_area_level_2")

            if region_abbreviation != None and region_abbreviation != location.region:
                location.region_abbreviation = region_abbreviation
                location.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0045_admintokens_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='region_abbreviation',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.RunPython(
            populate_regions_abbreviations, reverse_code=migrations.RunPython.noop),
    ]
