# Generated by Django 2.0.13 on 2019-08-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0046_location_region_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='region_abbreviation',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
