# Generated by Django 2.0.13 on 2019-09-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0047_auto_20190823_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.SmallIntegerField()),
                ('user_vendor', models.SmallIntegerField(choices=[(1, 'Entrep')], default=1)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='viral.UserProfile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='uservendor',
            unique_together={('user_vendor', 'user_profile')},
        ),
    ]
