# Generated by Django 2.0.13 on 2019-09-26 10:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0048_auto_20190924_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('endpoint', models.URLField(blank=True, default=None, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('auth_type', models.SmallIntegerField(choices=[(0, 'No Auth'), (1, 'Basic Auth')], default=0)),
                ('auth_user', models.CharField(blank=True, max_length=60, null=True)),
                ('auth_password', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='uservendor',
            name='user_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viral.Vendor'),
        ),
    ]
