# Generated by Django 2.0.13 on 2019-09-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0049_auto_20190926_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservendor',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
