# Generated by Django 2.0.13 on 2019-09-27 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0050_auto_20190927_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservendor',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viral.UserProfile'),
        ),
    ]
