# Generated by Django 2.0.13 on 2019-09-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0051_auto_20190927_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='uuid',
        ),
        migrations.AddField(
            model_name='vendor',
            name='uuid',
            field=models.IntegerField(unique=True),
        ),
    ]
