# Generated by Django 2.0.13 on 2019-10-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0052_auto_20190930_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservendor',
            name='user_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
