# Generated by Django 2.0.13 on 2019-10-02 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0053_auto_20191001_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viral.Company'),
        ),
    ]
