# Generated by Django 2.0.13 on 2019-11-05 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0054_auto_20191002_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('edit_any_company', 'Can edit any company')], 'verbose_name_plural': 'companies'},
        ),
    ]
