# Generated by Django 2.0.13 on 2019-11-26 10:17

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0020_questionbundle'),
        ('viral', '0055_auto_20191105_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='flow_type',
            field=models.IntegerField(choices=[(0, 'Self-Assessment flow'), (1, 'Program (Question Bundles) flow')], default=0),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='networks',
            field=models.ManyToManyField(blank=True, to='viral.Network'),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='question_bundles',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='matching.QuestionBundle'),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='supporters',
            field=models.ManyToManyField(blank=True, to='matching.Supporter'),
        ),
    ]
