# Generated by Django 2.0.13 on 2019-12-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0056_auto_20191126_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('schema', models.CharField(choices=[('program', 'Program (Question Bundles)')], default='program', max_length=128)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='affiliate',
            name='webhooks',
            field=models.ManyToManyField(blank=True, to='viral.AffiliateWebhook'),
        ),
    ]
