# Generated by Django 2.0.13 on 2019-12-11 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0019_auto_20190723_1121'),
        ('matching', '0022_question_shortname'),
        ('viral', '0057_auto_20191206_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProgramEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viral.Affiliate')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grid.Assessment')),
                ('responses', models.ManyToManyField(blank=True, to='matching.Response')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viral.UserProfile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='affiliateprogramentry',
            unique_together={('affiliate', 'assessment')},
        ),
    ]
