# Generated by Django 2.0.13 on 2019-12-16 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0058_auto_20191211_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateprogramentry',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viral.Affiliate'),
        ),
        migrations.AlterField(
            model_name='affiliateprogramentry',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.Assessment'),
        ),
        migrations.AlterField(
            model_name='affiliateprogramentry',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viral.UserProfile'),
        ),
    ]
