# Generated by Django 2.0.13 on 2020-01-08 11:23

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0059_auto_20191216_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='additional_emails',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None),
        ),
    ]
