# Generated by Django 2.0.13 on 2020-03-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0060_affiliate_additional_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(max_length=40, unique=True, null=True),
        ),
    ]
