# Generated by Django 2.0.13 on 2020-03-26 06:55

from django.db import migrations

from shared.models.unique_uid import model_populate_uids


def userprofile_populate_uids(apps, schema_editor):
    UserProfile = apps.get_model('viral', 'UserProfile')
    model_populate_uids(UserProfile)


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0061_userprofile_uuid'),
    ]

    operations = [
        migrations.RunPython(userprofile_populate_uids,
                             reverse_code=migrations.RunPython.noop)
    ]
