# Generated by Django 2.0.13 on 2020-04-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0062_auto_20200326_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='uid',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
