# Generated by Django 2.0.13 on 2020-04-07 08:37

from django.db import migrations

from shared.models.unique_uid import model_populate_uids


def populate_uids(apps, schema_editor):
    Company = apps.get_model('viral', 'Company')
    model_populate_uids(Company)


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0063_company_uid'),
    ]

    operations = [
        migrations.RunPython(populate_uids,
                             reverse_code=migrations.RunPython.noop)
    ]
