# Generated by Django 2.0.13 on 2020-05-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0064_auto_20200407_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='shortcode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='slug',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
    ]
