# Generated by Django 2.0.13 on 2020-06-04 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0065_auto_20200529_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetadata',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='metadata', related_query_name='metadata', to='viral.UserProfile'),
        ),
    ]
