# Generated by Django 2.0.13 on 2020-06-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0065_auto_20200604_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='slug',
            field=models.SlugField(max_length=80, null=True, unique=True),
        ),
    ]
