# Generated by Django 2.2.13 on 2020-07-10 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0066_network_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliateprogramentry',
            options={'verbose_name_plural': 'Affiliate Program Entries'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='viral.Company'),
        ),
    ]
