# Generated by Django 2.2.13 on 2020-07-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0066_network_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateprogramentry',
            name='uid',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
