# Generated by Django 2.2.13 on 2020-07-14 04:52

from django.db import migrations

from shared.models.unique_uid import model_populate_uids


def populate_uids(apps, schema_editor):
    AffiliateProgramEntry = apps.get_model('viral', 'AffiliateProgramEntry')
    model_populate_uids(AffiliateProgramEntry)


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0067_affiliateprogramentry_uid'),
    ]

    operations = [
        migrations.RunPython(populate_uids,
                             reverse_code=migrations.RunPython.noop)
    ]
