# Generated by Django 2.2.13 on 2020-07-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0068_auto_20200714_0452'),
        ('viral', '0067_auto_20200710_0609'),
    ]

    operations = [
    ]
