# Generated by Django 2.2.13 on 2020-07-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0069_merge_20200715_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliateprogramentry',
            options={'verbose_name_plural': 'Affiliate program entries'},
        ),
    ]
