# Generated by Django 2.2.13 on 2020-08-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0070_auto_20200724_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='groups',
            field=models.ManyToManyField(related_name='sectors', to='viral.Group'),
        ),
    ]
