# Generated by Django 2.2.13 on 2020-09-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0071_auto_20200819_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='location',
            name='groups',
            field=models.ManyToManyField(
                related_name='locations', to='viral.LocationGroup', blank=True),
        ),
    ]
