# Generated by Django 2.2.13 on 2020-11-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0072_auto_20200914_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='default_flow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='flow_target',
            field=models.IntegerField(choices=[(0, 'Entrepreneur'), (1, 'Supporter')], default=0),
        ),
    ]
