# Generated by Django 2.2.13 on 2020-11-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0073_auto_20201116_0455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliateprogramentry',
            options={'verbose_name': 'Affiliate Program - Entrepreneur submission', 'verbose_name_plural': 'Affiliate Program - Entrepreneur submissions'},
        ),
    ]
