# Generated by Django 2.2.13 on 2020-11-23 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0039_auto_20201119_1152'),
        ('viral', '0074_auto_20201119_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProgramSupporterSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=40, null=True, unique=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viral.Affiliate')),
                ('interests', models.ManyToManyField(blank=True, to='matching.Criteria')),
                ('responses', models.ManyToManyField(blank=True, to='matching.Response')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.Supporter')),
            ],
            options={
                'verbose_name': 'Affiliate Program - Supporter submission',
                'verbose_name_plural': 'Affiliate Program - Supporter submissions',
            },
        ),
    ]
