# Generated by Django 2.2.13 on 2020-12-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0041_auto_20201214_1248'),
        ('viral', '0075_affiliateprogramsupportersubmission'),
    ]

    operations = [
        migrations.RemoveField(model_name='affiliateprogramsupportersubmission', name='interests',),
        migrations.RemoveField(model_name='affiliateprogramsupportersubmission', name='responses',),
        migrations.AddField(
            model_name='affiliateprogramsupportersubmission', name='additional_criteria', field=models.ManyToManyField(
                blank=True, help_text='Optional responses outside of a Question Bundle.',
                related_name='additional_criteria', to='matching.Criteria'),),
        migrations.AddField(
            model_name='affiliateprogramsupportersubmission', name='criteria', field=models.ManyToManyField(
                blank=True, help_text='Responses given on a Question Bundle.', related_name='criteria',
                to='matching.Criteria'),), ]
