# Generated by Django 2.2.13 on 2020-12-18 06:27

import django.contrib.postgres.fields.ranges
from django.db import migrations
import matching.models.supporter


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0076_auto_20201214_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateprogramsupportersubmission',
            name='investing_level_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(null=True, validators=[matching.models.supporter.validate_level_range]),
        ),
    ]
