# Generated by Django 2.2.13 on 2021-01-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0077_affiliateprogramsupportersubmission_investing_level_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatewebhook',
            name='schema',
            field=models.CharField(choices=[('program', 'Entrepreneur Program (Question Bundles)'), ('supporter-program', 'Supporter Program (Question Bundles)')], default='program', max_length=128),
        ),
    ]
