# Generated by Django 2.2.13 on 2021-02-04 08:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0078_auto_20210120_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateprogramsupportersubmission',
            name='locations_of_interest',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliateprogramsupportersubmission',
            name='sectors_of_interest',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
