# Generated by Django 2.2.22 on 2021-07-27 09:37

from django.db import migrations, models
import viral.models.company


class Migration(migrations.Migration):

    dependencies = [
        ('company_lists', '0003_auto_20210323_0510'),
        ('viral', '0080_userguest'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='company_lists',
            field=models.ManyToManyField(blank=True, to='company_lists.CompanyList'),
        ),
        migrations.AlterField(
            model_name='company',
            name='access_hash',
            field=models.CharField(default=viral.models.company.unique_company_access_hash, max_length=10, null=True, unique=True),
        ),
    ]
