# Generated by Django 2.2.22 on 2021-08-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0081_auto_20210727_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='name_es',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='locationgroup',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='locationgroup',
            name='name_es',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='name_es',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
