# Generated by Django 2.2.22 on 2021-12-10 10:45

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0082_auto_20210820_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cors_origins',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text="Domains that are allowed to perform requests to Abaca's API.", null=True, size=None),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='endpoint',
            field=models.URLField(blank=True, default=None, help_text='Target URL to send back data to a Vendor.', null=True),
        ),
    ]
