# Generated by Django 2.2.22 on 2022-01-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0083_auto_20211210_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='callback_schema',
            field=models.CharField(choices=[('loose', 'Loose Schema'), ('loose_list', 'Loose List Schema')], default='loose_list', max_length=128),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='endpoint',
            field=models.URLField(blank=True, default=None, help_text='Callback URL to send back data to a Vendor.', null=True),
        ),
    ]
