# Generated by Django 2.2.28 on 2022-10-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0084_auto_20220126_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='company_lists',
            field=models.ManyToManyField(blank=True, related_name='_affiliate_company_lists_+', to='company_lists.CompanyList'),
        ),
    ]
