# Generated by Django 2.2.28 on 2022-11-14 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0085_auto_20221011_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
