# Generated by Django 2.2.28 on 2022-11-14 12:29

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0086_drop_legacy_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='show_team_section',
            field=models.BooleanField(default=False, help_text='Include the Team Section in this Affiliate flow'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viral.Company')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive Team Members will not be visible for the users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
