# Generated by Django 2.2.28 on 2022-11-25 05:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0087_add_team_member_related_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateprogramentry',
            name='team_members',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliateprogramsupportersubmission',
            name='team_members',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
