# Generated by Django 2.2.27 on 2023-06-19 11:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0089_affiliatesubmissiondraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='disclaimer_body',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='disclaimer_body_en',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='disclaimer_body_es',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='disclaimer_heading',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='disclaimer_heading_en',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='disclaimer_heading_es',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='questions_step_description',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='questions_step_description_en',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='questions_step_description_es',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='questions_step_note',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='questions_step_note_en',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='questions_step_note_es',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='self_assessment_step_description',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='self_assessment_step_description_en',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='self_assessment_step_description_es',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='self_assessment_step_note',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='self_assessment_step_note_en',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='self_assessment_step_note_es',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='summary',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='summary_en',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='summary_es',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='team_members_step_description',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='team_members_step_description_en',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='team_members_step_description_es',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='team_members_step_note',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='team_members_step_note_en',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='team_members_step_note_es',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
    ]
