# Generated by Django 2.2.27 on 2023-06-20 06:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0090_add_affiliate_landing_page_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='disclaimer_body',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 160 characters.'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='disclaimer_body_en',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 160 characters.', null=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='disclaimer_body_es',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 160 characters.', null=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='disclaimer_heading',
            field=models.CharField(blank=True, default='', help_text='This field will accept a maximum of 45 characters.', max_length=45),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='disclaimer_heading_en',
            field=models.CharField(blank=True, default='', help_text='This field will accept a maximum of 45 characters.', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='disclaimer_heading_es',
            field=models.CharField(blank=True, default='', help_text='This field will accept a maximum of 45 characters.', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='questions_step_description',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 100 characters. Keep in mind that there may be additional steps (self-assessment and team members).', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='questions_step_description_en',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 100 characters. Keep in mind that there may be additional steps (self-assessment and team members).', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='questions_step_description_es',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 100 characters. Keep in mind that there may be additional steps (self-assessment and team members).', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='questions_step_note',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 50 characters. This note is not commonly used.', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='questions_step_note_en',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 50 characters. This note is not commonly used.', null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='questions_step_note_es',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 50 characters. This note is not commonly used.', null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='self_assessment_step_description',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 100 characters. Keep in mind that there may be additional steps (questions and team members).', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='self_assessment_step_description_en',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 100 characters. Keep in mind that there may be additional steps (questions and team members).', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='self_assessment_step_description_es',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 100 characters. Keep in mind that there may be additional steps (questions and team members).', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='self_assessment_step_note',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 50 characters. This note is not commonly used.', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='self_assessment_step_note_en',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 50 characters. This note is not commonly used.', null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='self_assessment_step_note_es',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 50 characters. This note is not commonly used.', null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='summary',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 500 characters.'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='summary_en',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 500 characters.', null=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='summary_es',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 500 characters.', null=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='team_members_step_description',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 100 characters. Keep in mind that there may be additional steps (self-assessment and questions).', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='team_members_step_description_en',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 100 characters. Keep in mind that there may be additional steps (self-assessment and questions).', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='team_members_step_description_es',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 100 characters. Keep in mind that there may be additional steps (self-assessment and questions).', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='team_members_step_note',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 50 characters. This note is not commonly used.', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='team_members_step_note_en',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 50 characters. This note is not commonly used.', null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='team_members_step_note_es',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Try to limit this field to 50 characters. This note is not commonly used.', null=True, verbose_name='Note'),
        ),
    ]
