# Generated by Django 2.2.27 on 2023-10-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0091_adjust_affiliate_landing_page_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country_code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
