# Generated by Django 2.2.27 on 2023-10-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0092_location_country_code_google_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
