# Generated by Django 2.2.27 on 2024-01-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0094_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
