# Generated by Django 2.2.28 on 2025-11-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0095_subscription_fields_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='sdg_reports_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
