# Generated by Django 2.2.28 on 2025-11-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0096_affiliate_sdg_reports_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='flow_type',
            field=models.IntegerField(choices=[(0, 'Self-Assessment flow'), (1, 'Program (Question Bundles) flow'), (2, 'SDG (Sustainable Development Guide) flow')], default=0),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='sdg_reports_enabled',
            field=models.BooleanField(default=False, verbose_name='SDG Reports'),
        ),
    ]
