# Generated by Django 2.0.8 on 2018-08-29 11:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLevel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user', models.IntegerField()),
                ('evaluated', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('tip_title', models.TextField()),
                ('color', models.CharField(max_length=6)),
                ('abbreviation', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField(
                    db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CategoryLevel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('tip_description', models.TextField()),
                ('agent_expectation_likes', models.TextField()),
                ('agent_expectation_questions', models.TextField()),
                ('user_expectation_likes', models.TextField()),
                ('user_expectation_questions', models.TextField()),
                ('category', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='grid.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LevelFilter',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.IntegerField()),
                ('location', models.IntegerField()),
                ('category_level', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='grid.CategoryLevel')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='categorylevel',
            name='level',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='grid.Level'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='level',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='grid.Level'),
        ),
        migrations.AlterUniqueTogether(
            name='categorylevel',
            unique_together={('category', 'level')},
        ),
    ]
