# Generated by Django 2.0.8 on 2018-09-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='requirements_title',
        ),
        migrations.RenameField(
            model_name='categorylevel',
            old_name='tip_description',
            new_name='achievements',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tip_title',
        ),
        migrations.AddField(
            model_name='categorylevel',
            name='requirements',
            field=models.TextField(),
        ),
    ]
