# Generated by Django 2.0.8 on 2018-09-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_auto_20180918_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
