# Generated by Django 2.0.8 on 2018-09-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0003_level_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='abbreviation',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
