# Generated by Django 2.0.8 on 2018-09-21 11:10

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0004_auto_20180921_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylevel',
            name='requirements',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
