# Generated by Django 2.0.8 on 2018-09-24 08:43

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0005_auto_20180921_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylevel',
            name='achievements',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='categorylevel',
            name='description',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='categorylevel',
            name='requirements',
            field=markdownx.models.MarkdownxField(max_length=400),
        ),
    ]
