# Generated by Django 2.0.8 on 2018-11-21 04:08

from django.db import migrations, models
from grid.utils import generate_hash
import gspread
import os


def fix_evaluated_and_populate_hash_token(apps, schema_editor):
    Assessment = apps.get_model('grid', 'Assessment')
    UserProfile = apps.get_model('viral', 'UserProfile')
    for assessment in Assessment.objects.all():
        assessment.hash_token = generate_hash(assessment.created_at)
        try:
            user_profile = UserProfile.objects.get(user=assessment.user)
        except UserProfile.DoesNotExist:
            continue
        if user_profile.source:
            assessment.evaluated = user_profile.source.id
        assessment.save()


def update_spreadsheets(apps, schema_editor):
    Affiliate = apps.get_model('viral', 'Affiliate')
    Assessment = apps.get_model('grid', 'Assessment')
    for affiliate in Affiliate.objects.all():
        json_credentials = 'client_secret_development.json' if os.getenv(
            'DEBUG', 'False') == 'True' else 'client_secret.json'

        client = gspread.service_account(filename=json_credentials)

        title = 'Grid Viral Level - ' + affiliate.name
        spreadSheet = None
        try:
            spreadSheet = client.open(title)
        except gspread.SpreadsheetNotFound:
            break
        top_row = spreadSheet.sheet1.row_values(1)
        spreadSheet.sheet1.delete_row(1)
        top_row.append('Share link')
        spreadSheet.sheet1.insert_row(top_row, index=1)
        starting_row = 2
        for assessment in Assessment.objects.filter(evaluated=affiliate.id).order_by('created_at'):
            row = spreadSheet.sheet1.row_values(starting_row)
            spreadSheet.sheet1.delete_row(starting_row)
            row.append('https://' + os.getenv('APP_BASE_URL',
                                              'viral.vilcap.com') + '/assessment/' + assessment.hash_token)
            spreadSheet.sheet1.insert_row(row, index=starting_row)
            starting_row = starting_row + 1


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0006_auto_20180924_0843'),
        ('viral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='hash_token',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.RunPython(fix_evaluated_and_populate_hash_token,
                             reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='assessment',
            name='hash_token',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.RunPython(update_spreadsheets,
                             reverse_code=migrations.RunPython.noop),
    ]
