# Generated by Django 2.0.8 on 2018-11-26 03:31

from django.db import migrations


def fix_evaluated(apps, schema_editor):
    Assessment = apps.get_model('grid', 'Assessment')
    UserProfile = apps.get_model('viral', 'UserProfile')
    for assessment in Assessment.objects.all():
        try:
            user_profile = UserProfile.objects.get(user=assessment.user)
        except UserProfile.DoesNotExist:
            continue
        if user_profile.company:
            assessment.evaluated = user_profile.company.id
        assessment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0007_assessment_hash_token'),
    ]

    operations = [
        migrations.RunPython(fix_evaluated,
                             reverse_code=migrations.RunPython.noop),
    ]
