# Generated by Django 2.0.10 on 2019-02-08 04:32

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0008_auto_20181126_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
