# Generated by Django 2.0.10 on 2019-03-29 13:39

from django.db import migrations, models
import django.db.models.deletion


def add_category_groups(apps, schema_editor):
    CategoryGroup = apps.get_model('grid', 'CategoryGroup')
    Category = apps.get_model('grid', 'Category')
    supporters_group, created = CategoryGroup.objects.get_or_create(
        name='supporters')
    entrepreneurs_group, created = CategoryGroup.objects.get_or_create(
        name='entrepreneurs')

    # Iterate over existing categories and assign them to the entrepreneurs' group
    categories = Category.objects.all()
    for category in categories:
        category.group = entrepreneurs_group
        category.save()

    # Create new supporters category
    supporters = Category.objects.get_or_create(
        name='Companies Viral Range',
        group=supporters_group,
        abbreviation='VR',
        color='ff8141',
        requirements_title='Select a range of companies’ levels you’re interested in.',
        value_type='RANGE',
        order=1
    )


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0009_auto_20190208_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='value_type',
            field=models.CharField(
                choices=[('SINGLE', 'Single'), ('RANGE', 'Range')], default='SINGLE', max_length=6),
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='grid.CategoryGroup'),
        ),

        migrations.RunPython(add_category_groups)
    ]
