# Generated by Django 2.0.10 on 2019-03-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0010_auto_20190329_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorygroup',
            options={'verbose_name_plural': 'Category Groups'},
        ),
    ]
