# Generated by Django 2.0.10 on 2019-04-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0011_auto_20190329_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorygroup',
            old_name='name',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='value_type',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('RANGE', 'Range')], default='SINGLE', max_length=6),
        ),
    ]
