# Generated by Django 2.0.13 on 2019-05-23 13:39

from django.db import migrations, models

import django.db.models.deletion
import datetime

from .data.supporters import SUPPORTERS_LEVELS


def add_supporter_category_levels(apps, schema_editor):
    # TODO: Remove this function after fixing the fixtures
    CategoryGroup = apps.get_model('grid', 'CategoryGroup')
    Category = apps.get_model('grid', 'Category')
    CategoryLevel = apps.get_model('grid', 'CategoryLevel')
    Level = apps.get_model('grid', 'Level')

    # Create new supporters category
    supporter_category = Category.objects.get_or_create(
        name='Companies',
        group_id=1,
        abbreviation='C',
        color='ff8141',
        requirements_title='Select a range of companies’ levels you’re interested in.',
        value_type='RANGE',
        order=1
    )

    # Create supporters levels
    for level in SUPPORTERS_LEVELS:
        supporter_level = Level.objects.create(
            value=level['value'], title=level['title'], description=level['description'])

        CategoryLevel.objects.create(
            category=supporter_category[0],
            level=supporter_level,
            description=level['category_level']['description'],
            agent_expectation_likes=level['category_level']['agent_expectation_likes'],
            agent_expectation_questions=level['category_level']['agent_expectation_questions'],
            user_expectation_likes=level['category_level']['user_expectation_likes'],
            user_expectation_questions=level['category_level']['user_expectation_questions'],
            achievements=level['category_level']['achievements'],
            requirements=level['category_level']['requirements'])


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0012_auto_20190401_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylevel',
            name='achievements',
            field=models.CharField(max_length=160),
        ),
        # Deprecated in favor of: 0014_auto_20190529_1030
        # migrations.RunPython(add_supporter_category_levels)
    ]
