# Generated by Django 2.0.13 on 2019-05-29 10:30

from django.db import migrations, models
import django.db.models.deletion
from .data.supporters import SUPPORTERS_LEVELS


def add_level_groups(apps, schema_editor):
    CategoryLevel = apps.get_model('grid', 'CategoryLevel')
    Category = apps.get_model('grid', 'Category')
    CategoryGroup = apps.get_model('grid', 'CategoryGroup')
    LevelGroup = apps.get_model('grid', 'LevelGroup')
    Level = apps.get_model('grid', 'Level')

    # Add level groups
    supporters_level_group, created = LevelGroup.objects.get_or_create(
        slug='supporters')
    entrepreneurs_group, created = LevelGroup.objects.get_or_create(
        slug='entrepreneurs')

    # Iterate over existing levels and assign them to the entrepreneurs' group
    levels = Level.objects.all()
    for level in levels:
        level.group = entrepreneurs_group
        level.save()

    # Create supporters levels
    supporters_category_group = CategoryGroup.objects.get(slug='supporters')
    supporter_category = Category.objects.filter(
        group=supporters_category_group).first()

    for level in SUPPORTERS_LEVELS:
        supporter_level = Level.objects.create(
            value=level['value'], title=level['title'], description=level['description'], group=supporters_level_group)

        CategoryLevel.objects.create(
            category=supporter_category,
            level=supporter_level,
            description=level['category_level']['description'],
            agent_expectation_likes=level['category_level']['agent_expectation_likes'],
            agent_expectation_questions=level['category_level']['agent_expectation_questions'],
            user_expectation_likes=level['category_level']['user_expectation_likes'],
            user_expectation_questions=level['category_level']['user_expectation_questions'],
            achievements=level['category_level']['achievements'],
            requirements=level['category_level']['requirements'])


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0013_auto_20190523_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Level Groups',
            },
        ),
        migrations.AddField(
            model_name='level',
            name='group',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='grid.LevelGroup'),
        ),
        migrations.RunPython(add_level_groups)
    ]
