# Generated by Django 2.0.13 on 2019-06-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0014_auto_20190529_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorylevel',
            old_name='agent_expectation_likes',
            new_name='achieved_milestones_description',
        ),
        migrations.RenameField(
            model_name='categorylevel',
            old_name='agent_expectation_questions',
            new_name='achieved_milestones_title',
        ),
        migrations.RenameField(
            model_name='categorylevel',
            old_name='user_expectation_likes',
            new_name='next_milestones_description',
        ),
        migrations.RenameField(
            model_name='categorylevel',
            old_name='user_expectation_questions',
            new_name='next_milestones_title',
        ),
    ]
