# Generated by Django 2.0.13 on 2019-07-01 10:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0015_auto_20190619_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylevel',
            name='achieved_milestones_description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='categorylevel',
            name='achieved_milestones_title',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='categorylevel',
            name='next_milestones_description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='categorylevel',
            name='next_milestones_title',
            field=tinymce.models.HTMLField(),
        ),
    ]
