# Generated by Django 2.0.13 on 2019-07-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0016_auto_20190701_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='state',
            field=models.IntegerField(choices=[(0, 'Began Assessment'), (1, 'Finished Assessment'), (2, 'Registered User Assessment')], default=2),
        ),
    ]
