# Generated by Django 2.0.13 on 2019-07-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0017_assessment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'Began Assessment'), (1, 'Finished Assessment'), (2, 'Registered User Assessment')], default=2),
        ),
    ]
