# Generated by Django 2.0.13 on 2019-07-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0018_auto_20190717_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'Began Assessment'), (1, 'Finished Assessment'), (2, 'User Registered')], default=2),
        ),
    ]
