# Generated by Django 2.2.22 on 2021-08-20 04:48

from django.db import migrations, models
import markdownx.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0019_auto_20190723_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='abbreviation_en',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='abbreviation_es',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='requirements_title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='requirements_title_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='categorylevel',
            name='achieved_milestones_description_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='categorylevel',
            name='achieved_milestones_description_es',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='categorylevel',
            name='achieved_milestones_title_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='categorylevel',
            name='achieved_milestones_title_es',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='categorylevel',
            name='achievements_en',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='categorylevel',
            name='achievements_es',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='categorylevel',
            name='description_en',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='categorylevel',
            name='description_es',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='categorylevel',
            name='next_milestones_description_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='categorylevel',
            name='next_milestones_description_es',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='categorylevel',
            name='next_milestones_title_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='categorylevel',
            name='next_milestones_title_es',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='categorylevel',
            name='requirements_en',
            field=markdownx.models.MarkdownxField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='categorylevel',
            name='requirements_es',
            field=markdownx.models.MarkdownxField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='description_en',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='description_es',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='title_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='title_es',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
