# Generated by Django 2.2.22 on 2021-08-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0020_auto_20210820_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='from_milestone_planner',
            field=models.BooleanField(default=False, help_text='Signals assessments that were generated from completing or uncompleting a milestone'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='evaluated',
            field=models.IntegerField(help_text='Company ID'),
        ),
    ]
