# Generated by Django 2.2.22 on 2021-09-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0021_assessment_from_milestone_planner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
    ]
