# Generated by Django 2.2.22 on 2021-11-18 07:32

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0022_auto_20210909_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='typical_funding',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AddField(
            model_name='level',
            name='typical_funding_en',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='typical_funding_es',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
