# Generated by Django 2.2.13 on 2020-12-18 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0077_affiliateprogramsupportersubmission_investing_level_range'),
        ('shared', '0002_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='affiliate',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pending_registration',
                to='viral.Affiliate'),
        ),
    ]
