# Generated by Django 2.2.28 on 2026-01-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='consent_type',
            field=models.CharField(choices=[('capital_explorer', 'Capital Explorer'), ('sdg_report', 'SDG Report')], max_length=128),
        ),
    ]
