# Generated by Django 2.2.28 on 2026-01-13 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_auto_20260113_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consent',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.RemoveConstraint(
            model_name='consent',
            name='unique_user_consent',
        ),
    ]
