# Generated by Django 2.2.27 on 2023-05-11 09:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import shared.validators
import sortedm2m.fields
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0065_questionbundle_capital_explorer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundingStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('about', tinymce.models.HTMLField()),
                ('key_characteristics', tinymce.models.HTMLField()),
                ('key_implications', tinymce.models.HTMLField()),
                ('company_stages', sortedm2m.fields.SortedManyToManyField(help_text=None, to='capital_explorer.CompanyStage')),
                ('funding_stages', sortedm2m.fields.SortedManyToManyField(help_text=None, to='capital_explorer.FundingStage')),
                ('funding_types', sortedm2m.fields.SortedManyToManyField(help_text=None, to='capital_explorer.FundingType')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundingCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desired', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON object specifying the desired value:\n        { "text": "" } or { "value": 1 } or { "min": 5, "max": 9 }', null=True, validators=[shared.validators.JSONSchemaValidator(limit_value={'oneOf': [{'required': ['value']}, {'required': ['min', 'max']}, {'required': ['text']}, {'required': ['date']}], 'properties': {'date': {'type': 'string'}, 'max': {'type': 'number'}, 'min': {'type': 'number'}, 'text': {'type': 'string'}, 'value': {'type': 'number'}}, 'type': 'object'})])),
                ('answers', models.ManyToManyField(blank=True, to='matching.Answer')),
                ('criteria_weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.CriteriaWeight')),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capital_explorer.FundingSource')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.Question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Funding criteria',
            },
        ),
    ]
