# Generated by Django 2.2.27 on 2023-07-31 04:39

from django.db import migrations, models
import django.db.models.deletion

from capital_explorer.models import CriteriaWeight

def create_criteria_weights(apps, schema_editor):
    CriteriaWeight.objects.bulk_create(
        [
            CriteriaWeight(id=1, name='Irrelevant', value_matched=0, value_unmatched=0, value_unanswered=0),
            CriteriaWeight(id=2, name='A Little Important', value_matched=1, value_unmatched=1, value_unanswered=1),
            CriteriaWeight(id=3, name='Somewhat Important', value_matched=10, value_unmatched=10, value_unanswered=10),
            CriteriaWeight(id=4, name='Very Important', value_matched=50, value_unmatched=50, value_unanswered=50),
            CriteriaWeight(id=5, name='Extremely Important', value_matched=250, value_unmatched=500, value_unanswered=350),
        ]
    )

class Migration(migrations.Migration):

    dependencies = [
        ('capital_explorer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value_matched', models.IntegerField()),
                ('value_unmatched', models.IntegerField()),
                ('value_unanswered', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.RunPython(create_criteria_weights, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fundingcriteria',
            name='criteria_weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capital_explorer.CriteriaWeight'),
        ),
    ]
