# Generated by Django 2.2.27 on 2023-08-01 08:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_explorer', '0002_criteriaweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsource',
            name='related_links',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
