# Generated by Django 2.2.27 on 2023-08-08 05:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import shared.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0091_adjust_affiliate_landing_page_fields'),
        ('capital_explorer', '0003_fundingsource_related_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital_explorer_submissions', to='viral.Company')),
                ('responses', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[shared.validators.JSONSchemaValidator(limit_value={'items': {'properties': {'answers': {'items': {'type': 'number'}, 'type': 'array'}, 'question': {'type': 'number'}}, 'required': ['question', 'answers'], 'type': 'object'}, 'type': 'array'})])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
