# Generated by Django 2.2.27 on 2023-08-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_explorer', '0004_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='passcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='previous_passcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
