# Generated by Django 2.2.27 on 2023-08-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0091_adjust_affiliate_landing_page_fields'),
        ('capital_explorer', '0005_submission_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='invited_guests',
            field=models.ManyToManyField(blank=True, to='viral.UserGuest'),
        ),
        migrations.AddField(
            model_name='submission',
            name='invited_users',
            field=models.ManyToManyField(blank=True, to='viral.UserProfile'),
        ),
    ]
