# Generated by Django 2.2.27 on 2023-08-24 11:01

from django.db import migrations, models
from shared.models.unique_uid import model_populate_uids


def populate_uids(apps, schema_editor):
    Submission = apps.get_model('capital_explorer', 'Submission')
    model_populate_uids(Submission)


class Migration(migrations.Migration):
    dependencies = [
        ('capital_explorer', '0006_submission_invited_users_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='uid',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.RunPython(populate_uids, reverse_code=migrations.RunPython.noop)
    ]
