# Generated by Django 2.2.22 on 2021-08-13 09:56

from django.conf import settings
from django.db import migrations, models
from django.db.models import OuterRef, Subquery
import django.db.models.deletion
import milestone_planner.models.milestone
import simple_history.models


def generate_milestones_from_assessments(apps, schema_editor):
    Milestone = apps.get_model('milestone_planner', 'Milestone')
    Assessment = apps.get_model('grid', 'Assessment')
    UserProfile = apps.get_model('viral', 'UserProfile')

    # Grab every latest assessment as well as its user profile primary key:
    latest_assessments = Assessment.objects.distinct('evaluated').order_by('evaluated', '-created_at').annotate(
        user_profile_pk=Subquery(UserProfile.objects.filter(company__pk=OuterRef('evaluated')).values('pk')))
    
    # TEMPORARY FIX FOR ASSESSMENTS WITH INVALID USER PROFILES:
    valid_assessments = [assessment for assessment in latest_assessments if assessment.user_profile_pk is not None]

    return Milestone.objects.generate_from_assessments(assessments=valid_assessments)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grid', '0021_assessment_from_milestone_planner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0052_historicalresponse'),
        ('viral', '0081_auto_20210727_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMilestone',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('critical', models.BooleanField(default=False)),
                ('strategy', models.TextField(blank=True)),
                ('outcomes', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('finances_needed', models.PositiveIntegerField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('plan_published', models.BooleanField(default=False)),
                ('evidence_published', models.BooleanField(default=False)),
                ('date_of_completion', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('to-be-planned', 'To Be Planned'), ('planned', 'Planned'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='completed', max_length=128)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical milestone',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=40, null=True, unique=True)),
                ('critical', models.BooleanField(default=False)),
                ('strategy', models.TextField(blank=True)),
                ('outcomes', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('finances_needed', models.PositiveIntegerField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('plan_published', models.BooleanField(default=False)),
                ('evidence_published', models.BooleanField(default=False)),
                ('date_of_completion', models.DateField(blank=True, null=True)),
                ('category_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='grid.CategoryLevel')),
                ('evidence', models.ManyToManyField(blank=True, help_text='Responses given as evidence of a Milestone completed.', related_name='milestones', to='matching.Response')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='viral.UserProfile')),
                ('state', models.CharField(choices=[('to-be-planned', 'To Be Planned'), ('planned', 'Planned'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='completed', max_length=128)),
            ],
            options={
                'unique_together': {('user_profile', 'category_level')},
            },
            managers=[
                ('objects', milestone_planner.models.milestone.MilestoneManager()),
            ],
        ),
        migrations.RunPython(generate_milestones_from_assessments, reverse_code=migrations.RunPython.noop)
    ]
