# Generated by Django 2.2.22 on 2022-02-02 06:54

from django.db import migrations, models
import django.db.models.deletion

from shared.models.unique_uid import random_uid


def generate_milestone_planners(apps, schema_editor):
    Milestone = apps.get_model('milestone_planner', 'Milestone')
    MilestonePlanner = apps.get_model('milestone_planner', 'MilestonePlanner')

    distinct_milestones_by_user = Milestone.objects.distinct('user_profile').all()

    # Create a milestone planner for each company that has milestones:
    MilestonePlanner.objects.bulk_create([
        MilestonePlanner(
            uid=random_uid(),
            company=milestone.user_profile.company)
        for milestone in distinct_milestones_by_user])


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0084_auto_20220126_0556'),
        ('milestone_planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestonePlanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=40, null=True, unique=True)),
                ('passcode', models.CharField(blank=True, max_length=20, null=True)),
                ('previous_passcode', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_planners', to='viral.Company')),
                ('invited_guests', models.ManyToManyField(blank=True, to='viral.UserGuest')),
                ('invited_users', models.ManyToManyField(blank=True, to='viral.UserProfile')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.RunPython(generate_milestone_planners, reverse_code=migrations.RunPython.noop)
    ]
