# Generated by Django 2.2.27 on 2024-01-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0095_subscription_fields_max_length'),
        ('milestone_planner', '0002_milestoneplanner'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.CreateModel(
                name='UserInvitation',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ],
                options={
                    'db_table': 'milestone_planner_milestoneplanner_invited_users',
                },
            ),
            migrations.AlterField(
                model_name='milestoneplanner',
                name='invited_users',
                field=models.ManyToManyField(blank=True, through='milestone_planner.UserInvitation', to='viral.UserProfile'),
            ),
            migrations.AddField(
                model_name='userinvitation',
                name='milestoneplanner',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milestone_planner.MilestonePlanner'),
            ),
            migrations.AddField(
                model_name='userinvitation',
                name='userprofile',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viral.UserProfile'),
            ),
            migrations.AlterUniqueTogether(
                name='userinvitation',
                unique_together={('milestoneplanner', 'userprofile')},
            ),
        ])
    ]
