# Generated by Django 2.2.27 on 2024-01-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone_planner', '0003_userinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='is_form_owner',
            field=models.BooleanField(default=False),
        ),
    ]
