# Generated by Django 2.0.10 on 2019-01-24 12:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('weight', models.IntegerField()),
                ('desired', django.contrib.postgres.fields.jsonb.JSONField()),
                ('answer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='matching.Answer')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepreneur_question', models.CharField(max_length=100)),
                ('resource_question', models.CharField(max_length=100)),
                ('ttl', models.DurationField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'question categories',
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(
                    blank=True, null=True)),
                ('question', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='matching.Question')),
                ('user_profile', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='viral.UserProfile')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('locations', models.ManyToManyField(to='viral.Location')),
                ('sectors', models.ManyToManyField(to='viral.Sector')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupporterType',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='supporter',
            name='types',
            field=models.ManyToManyField(to='matching.SupporterType'),
        ),
        migrations.AddField(
            model_name='supporter',
            name='user_profile',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='viral.UserProfile'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='matching.QuestionCategory'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='matching.QuestionType'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='question',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='matching.Question'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='supporter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='matching.Supporter'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='matching.Question'),
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='answer',
        ),
        migrations.AlterField(
            model_name='criteria',
            name='desired',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CriteriaWeight',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='criteria',
            name='weight',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='matching.CriteriaWeight'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='answer',
            field=models.ManyToManyField(blank=True, to='matching.Answer'),
        ),
        migrations.AddField(
            model_name='response',
            name='answers',
            field=models.ManyToManyField(blank=True, to='matching.Answer'),
        ),
    ]
