# Generated by Django 2.0.10 on 2019-01-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name_plural': 'question categories'},
        ),
    ]
