# Generated by Django 2.0.10 on 2019-01-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20190124_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criteria',
            old_name='weight',
            new_name='criteria_weight',
        ),
    ]
