# Generated by Django 2.0.10 on 2019-01-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_auto_20190125_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criteria',
            old_name='answer',
            new_name='answers',
        ),
    ]
