# Generated by Django 2.0.10 on 2019-02-13 10:09

import django.contrib.postgres.fields.ranges
from django.db import migrations
import matching.models.supporter


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_auto_20190125_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter',
            name='investing_level_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(
                default="[1,10)", validators=[matching.models.supporter.validate_level_range]),
            preserve_default=False,
        ),
    ]
