# Generated by Django 2.0.10 on 2019-02-14 12:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_supporter_investing_level_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='questiontype',
            name='type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('single-select', 'Single Select'), ('multi-select', 'Multi Select'), ('range', 'Range')], default='single-select', max_length=50),
        ),
    ]
