# Generated by Django 2.0.10 on 2019-02-15 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_auto_20190214_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter',
            name='level_weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='matching.CriteriaWeight'),
        ),
        migrations.AddField(
            model_name='supporter',
            name='locations_weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='matching.CriteriaWeight'),
        ),
        migrations.AddField(
            model_name='supporter',
            name='sectors_weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='matching.CriteriaWeight'),
        ),
    ]
