# Generated by Django 2.0.8 on 2019-03-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_auto_20190215_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='viral.Sector'),
        ),
    ]
