# Generated by Django 2.0.10 on 2019-04-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_auto_20190308_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='locations',
            field=models.ManyToManyField(blank=True, to='viral.Location'),
        ),
    ]
