# Generated by Django 2.0.13 on 2019-05-24 09:42

from django.db import migrations, models


def set_public_types(apps, schema_editor):
    SupporterType = apps.get_model('matching', 'SupporterType')
    types = SupporterType.objects.all()

    SupporterType.objects.create(
        name='Pro Service', description='', label='Legal, Banking, Accounting, etc.', public=True)

    default_public_types = ['Investor', 'Lender', 'Acceleration',
                            'Workspace', 'Incubator', 'Grants', 'Small Business', 'Pro Service']

    for supporter_type in types:
        if supporter_type.name in default_public_types:
            supporter_type.public = True
            supporter_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_auto_20190422_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportertype',
            name='label',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supportertype',
            name='public',
            field=models.BooleanField(default=False),
        ),
        # migrations.RunPython(set_public_types)
    ]
