# Generated by Django 2.0.13 on 2019-05-28 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0010_auto_20190524_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupporterOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupporterOfferingCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupporterOfferingTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('supporter_offering_categories', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='matching.SupporterOfferingCategories')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='supporteroffering',
            name='supporter_offering_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='matching.SupporterOfferingCategories'),
        ),
        migrations.AddField(
            model_name='supporteroffering',
            name='supporter_offering_types',
            field=models.ManyToManyField(blank=True, null=True, to='matching.SupporterOfferingTypes'),
        ),
    ]
