# Generated by Django 2.0.13 on 2019-05-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0011_auto_20190528_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporteroffering',
            name='supporter_offering_types',
            field=models.ManyToManyField(blank=True, to='matching.SupporterOfferingTypes'),
        ),
    ]
