# Generated by Django 2.0.13 on 2019-05-29 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0012_auto_20190529_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporteroffering',
            name='supporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.Supporter'),
        ),
    ]
