# Generated by Django 2.0.13 on 2019-05-29 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0013_supporteroffering_supporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supporteroffering',
            old_name='supporter_offering_categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='supporteroffering',
            old_name='supporter_offering_types',
            new_name='types',
        ),
        migrations.RenameField(
            model_name='supporterofferingtypes',
            old_name='supporter_offering_categories',
            new_name='categories',
        ),
    ]
