# Generated by Django 2.0.13 on 2019-05-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0014_auto_20190529_0538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supporterofferingtypes',
            old_name='categories',
            new_name='category',
        ),
    ]
