# Generated by Django 2.0.13 on 2019-05-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0015_auto_20190529_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supporter',
            options={'verbose_name_plural': 'supporters'},
        ),
    ]
