# Generated by Django 2.0.13 on 2019-05-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0016_auto_20190529_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
