# Generated by Django 2.0.13 on 2019-08-08 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0045_admintokens_available'),
        ('matching', '0017_auto_20190529_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedCTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supporter_is_interested', models.IntegerField(choices=[(0, 'Initial Value'), (1, 'Interest'), (2, 'Connected'), (3, 'Connected before')], default=0)),
                ('entrepeneur_is_interested', models.IntegerField(choices=[(0, 'Initial Value'), (1, 'Interest'), (2, 'Connected'), (3, 'Connected before')], default=0)),
                ('state_of_interest', models.IntegerField(choices=[(0, 'Initial Value'), (1, 'Interest'), (2, 'Connected'), (3, 'Connected before')], default=0)),
                ('entrepeneur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrepeneur_company_id', to='viral.Company')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='supporter_company_id', to='viral.Company')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='interestedcta',
            unique_together={('supporter', 'entrepeneur')},
        ),
    ]
