# Generated by Django 2.0.13 on 2019-08-09 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0045_admintokens_available'),
        ('matching', '0018_auto_20190808_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestedcta',
            old_name='entrepeneur_is_interested',
            new_name='entrepreneur_is_interested',
        ),
        migrations.RenameField(
            model_name='interestedcta',
            old_name='entrepeneur',
            new_name='entrepreneur',
        ),
        migrations.AlterField(
            model_name='interestedcta',
            name='entrepreneur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='entrepreneur_company_id', to='viral.Company'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='interestedcta',
            unique_together={('supporter', 'entrepreneur')},
        ),
    ]
