# Generated by Django 2.0.13 on 2019-11-26 10:17

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0019_auto_20190809_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('questions', sortedm2m.fields.SortedManyToManyField(help_text=None, to='matching.Question')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.Supporter')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
