# Generated by Django 2.0.13 on 2019-12-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0020_questionbundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('single-select', 'Single Select'), ('multi-select', 'Multi Select'), ('range', 'Range'), ('free-response', 'Free Response')], default='single-select', max_length=50),
        ),
    ]
