# Generated by Django 2.0.13 on 2019-12-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0021_auto_20191204_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='shortname',
            field=models.SlugField(max_length=80, null=True, unique=True),
        ),
    ]
