# Generated by Django 2.0.13 on 2020-01-21 06:24
import os

from django.db import migrations
from django.apps import apps

from shared.execute_raw_sql import ExecuteRawSQL

# Specify algorithm version and directory path containing SQL files
algorithm_version = '1.0.0'
algorithm_path = apps.get_app_config(
    'matching').path + '/algorithm/' + algorithm_version

# Specify which SQL files to run and in which order to execute
algorithm_list = [
    '01_create_materialise_settings',
    '02_create_levels_scores',
    '03_create_locations_scores',
    '04_create_sectors_scores',
    '05_create_responses_scores',
    '06_create_matching_total_scores',
    '07_create_matching_triggers',
]

# Instantiate class that will execute SQL files through migration
algorithm = ExecuteRawSQL(algorithm_path, algorithm_list)


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0022_question_shortname'),
    ]

    operations = [
        migrations.RunPython(algorithm.load_sql),
    ]
