# Generated by Django 2.0.13 on 2020-01-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0023_inital_materialised'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingTotalScores',
            fields=[
                ('company_id', models.IntegerField(
                    primary_key=True, serialize=False)),
                ('supporter_id', models.IntegerField(primary_key=True)),
                ('max_score_percentil', models.IntegerField()),
            ],
            options={
                'db_table': 'matching"."total_score',
                'managed': False,
            },
        ),
    ]
