# Generated by Django 2.0.13 on 2020-01-23 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0024_matchingtotalscores'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingAlgorithmResults',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING,
                                                 primary_key=True, serialize=False, to='viral.Company')),
                ('supporter', models.OneToOneField(
                    on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, to='matching.Supporter')),
                ('max_score_percentil', models.IntegerField(verbose_name='Score %')),
            ],
            options={
                'verbose_name_plural': 'Matching Algorithm Results',
                'db_table': 'matching"."total_score',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='supporterofferingcategories',
            options={'verbose_name_plural': 'Supporter offering categories'},
        ),
        migrations.AlterModelOptions(
            name='supporterofferingtypes',
            options={'verbose_name_plural': 'Supporter offering types'},
        ),
    ]
