# Generated by Django 2.0.13 on 2020-01-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0026_match_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingAlgorithms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Algorithms',
                'db_table': 'matching"."algorithm',
                'managed': False,
            },
        ),
    ]
