# Generated by Django 2.0.13 on 2020-03-24 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0029_drop_matching_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestedcta',
            name='entrepreneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneur_company_id', to='viral.Company'),
        ),
        migrations.AlterField(
            model_name='interestedcta',
            name='supporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporter_company_id', to='viral.Company'),
        ),
    ]
