# Generated by Django 2.0.13 on 2020-04-07 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0030_auto_20200324_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporter', to='viral.UserProfile'),
        ),
    ]
