# Generated by Django 2.0.13 on 2020-05-13 19:31
from django.db import migrations
from django.apps import apps

from shared.execute_raw_sql import ExecuteRawSQL

# Specify algorithm version and directory path containing SQL files
algorithm_version = '1.0.5'
algorithm_path = apps.get_app_config(
    'matching').path + '/algorithm/' + algorithm_version

# Instantiate class that will execute SQL files through migration
algorithm = ExecuteRawSQL(algorithm_path, list=['alter_distinct_views', 'update_algorithm_settings'])


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0032_update_penalisation_algorithm'),
    ]

    operations = [
        migrations.RunPython(algorithm.load_sql),
    ]
