# Generated by Django 2.2.13 on 2020-07-06 02:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0033_add_new_algorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='MatchingAlgorithmResults',
        ),
    ]
