# Generated by Django 2.2.13 on 2020-07-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0034_auto_20200706_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupporterWizard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('matching.supporter',),
        ),
        migrations.AlterModelOptions(
            name='interestedcta',
            options={'verbose_name': 'Connection'},
        ),
    ]
