# Generated by Django 2.2.13 on 2020-07-24 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('matching', '0035_auto_20200710_0609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supporterwizard',
            options={'verbose_name': 'Complete Supporter', 'verbose_name_plural': 'Supporters Wizard'},
        ),
        migrations.AddField(
            model_name='question',
            name='profile_field',
            field=models.ForeignKey(blank=True, help_text="Optionally target a profile field where the response to a question will override that field's value", null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.ProfileIDField'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('single-select', 'Single Select'), ('multi-select', 'Multi Select'), ('range', 'Range'), ('free-response', 'Free Response'), ('date', 'Date')], default='single-select', max_length=50),
        ),
    ]
