# Generated by Django 2.2.13 on 2020-09-01 11:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0071_auto_20200819_1258'),
        ('matching', '0036_auto_20200724_0610'),
    ]

    operations = [
        # Adding extra field (group) on existing m2m relation
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='SupporterInterestSector',
                    fields=[
                        ('id', models.AutoField(auto_created=True,
                                                primary_key=True, serialize=False, verbose_name='ID')),
                        ('sector', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE, to='viral.Sector')),
                    ],
                    options={
                        'db_table': 'matching_supporter_sectors',
                        'verbose_name_plural': 'Sectors Of Interest'
                    },
                ),
                migrations.AlterField(
                    model_name='supporter',
                    name='sectors',
                    field=models.ManyToManyField(
                        blank=True, through='matching.SupporterInterestSector', to='viral.Sector'),
                ),
                migrations.AddField(
                    model_name='supporterinterestsector',
                    name='supporter',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='matching.Supporter', related_name='sectors_of_interest'),
                ),
                migrations.AlterUniqueTogether(
                    name='supporterinterestsector',
                    unique_together={('supporter', 'sector')},
                ),
            ]
        ),
        migrations.AddField(
            model_name='supporterinterestsector',
            name='group',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viral.Group'),
        ),

        # Documentating fields
        migrations.AlterField(
            model_name='criteria',
            name='answers',
            field=models.ManyToManyField(
                blank=True, help_text='Chosen Answers IDs', to='matching.Answer'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='criteria_weight',
            field=models.ForeignKey(help_text='Criteria weight ID',
                                    on_delete=django.db.models.deletion.CASCADE, to='matching.CriteriaWeight'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='desired',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, help_text='JSON object specifying the desired numeric value: { "value": 1 } or { "min": 5, "max": 10 }', null=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='question',
            field=models.ForeignKey(
                help_text='Question ID', on_delete=django.db.models.deletion.CASCADE, to='matching.Question'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='supporter',
            field=models.ForeignKey(
                help_text='Supporter ID', on_delete=django.db.models.deletion.CASCADE, to='matching.Supporter'),
        ),
        migrations.AlterField(
            model_name='interestedcta',
            name='entrepreneur',
            field=models.ForeignKey(help_text='Company ID of Entrepreneur', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='entrepreneur_company_id', to='viral.Company'),
        ),
        migrations.AlterField(
            model_name='interestedcta',
            name='entrepreneur_is_interested',
            field=models.IntegerField(choices=[(0, 'Initial Value'), (1, 'Interest'), (2, 'Connected'), (
                3, 'Connected before')], default=0, help_text='0 (Initial) 1 (Interested)'),
        ),
        migrations.AlterField(
            model_name='interestedcta',
            name='state_of_interest',
            field=models.IntegerField(choices=[(0, 'Initial Value'), (1, 'Interest'), (2, 'Connected'), (
                3, 'Connected before')], default=0, help_text='0 (No connection) 1 (Someone has interest) 2 (Connected) 3 (Disconnected)'),
        ),
        migrations.AlterField(
            model_name='interestedcta',
            name='supporter',
            field=models.ForeignKey(help_text='Company ID of Supporter', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='supporter_company_id', to='viral.Company'),
        ),
        migrations.AlterField(
            model_name='interestedcta',
            name='supporter_is_interested',
            field=models.IntegerField(choices=[(0, 'Initial Value'), (1, 'Interest'), (2, 'Connected'), (
                3, 'Connected before')], default=0, help_text='0 (Initial) 1 (Interested)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='answers',
            field=models.ManyToManyField(
                blank=True, help_text='Chosen Answers IDs', to='matching.Answer'),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(
                help_text='Question ID', on_delete=django.db.models.deletion.CASCADE, to='matching.Question'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user_profile',
            field=models.ForeignKey(
                help_text='User Profile ID', on_delete=django.db.models.deletion.CASCADE, to='viral.UserProfile'),
        ),
        migrations.AlterField(
            model_name='response',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, help_text='JSON object specifying a numeric value: { "value": 1 } or { "min": 5, "max": 10 }', null=True),
        ),
    ]
