# Generated by Django 2.2.13 on 2020-09-14 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0072_auto_20200914_0804'),
        ('matching', '0037_auto_20200901_1147'),
    ]

    operations = [
        # Wrapped in SeparateDatabaseAndState to avoid recreating m2m relation
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='SupporterInterestLocation',
                    fields=[
                        ('id', models.AutoField(auto_created=True,
                                                primary_key=True, serialize=False, verbose_name='ID')),
                        ('location', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE, to='viral.Location')),
                    ],
                    options={
                        'verbose_name_plural': 'Locations Of Interest',
                        'db_table': 'matching_supporter_locations',
                    },
                ),
                migrations.AlterField(
                    model_name='supporter',
                    name='locations',
                    field=models.ManyToManyField(
                        blank=True, through='matching.SupporterInterestLocation', to='viral.Location'),
                ),
                migrations.AddField(
                    model_name='supporterinterestlocation',
                    name='supporter',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='locations_of_interest', to='matching.Supporter'),
                ),
                migrations.AlterUniqueTogether(
                    name='supporterinterestlocation',
                    unique_together={('supporter', 'location')},
                ),
            ]
        ),

        # Adding extra field (group) on existing m2m relation
        migrations.AddField(
            model_name='supporterinterestlocation',
            name='group',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viral.LocationGroup'),
        ),
    ]
