# Generated by Django 2.2.13 on 2020-11-19 11:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import shared.validators


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0038_auto_20200914_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='shortname',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='question',
            name='short_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='desired',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='\n        JSON object specifying the desired value or range:\n        { "value": 1 } or { "min": 5, "max": 10 }', null=True, validators=[shared.validators.JSONSchemaValidator(limit_value={'oneOf': [{'required': ['value']}, {'required': ['min', 'max']}], 'properties': {'max': {'type': 'integer'}, 'min': {'type': 'integer'}, 'value': {'type': 'integer'}}, 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='response',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='\n        JSON object specifying the value and type:\n        { "text": "" } or { "value": 1 } or { "min": 5, "max": 10 }', null=True, validators=[shared.validators.JSONSchemaValidator(limit_value={'oneOf': [{'required': ['text']}, {'required': ['value']}], 'properties': {'text': {'type': 'string'}, 'value': {'oneOf': [{'type': 'integer'}, {'oneOf': [{'properties': {'max': {'type': 'integer'}, 'min': {'type': 'integer'}}, 'required': ['min', 'max']}], 'type': 'object'}]}}, 'type': 'object'})]),
        ),
    ]
