# Generated by Django 2.2.13 on 2020-11-25 10:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import shared.validators


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0039_auto_20201119_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='question', name='is_common', field=models.BooleanField(
                default=False, help_text='Set question as most common for additional criteria'),),
        migrations.AlterField(
            model_name='criteria', name='desired', field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                help_text='JSON object specifying the desired value or range: { "value": 1 } or { "min": 5, "max": 10 }',
                null=True,
                validators=[shared.validators.JSONSchemaValidator(
                    limit_value={'oneOf': [{'required': ['value']},
                                           {'required': ['min', 'max']}],
                                 'properties':
                                 {'max': {'type': 'integer'},
                                  'min': {'type': 'integer'},
                                  'value': {'type': 'integer'}},
                                 'type': 'object'})]),),
        migrations.AlterField(
            model_name='response', name='value', field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                help_text='JSON object specifying the value: { "text": "" } or { "value": 1 } or { "min": 5, "max": 9 }',
                null=True,
                validators=[shared.validators.JSONSchemaValidator(
                    limit_value={
                        'oneOf':
                        [{'required': ['text']},
                         {'required': ['value']},
                         {'required': ['date']},
                         {'required': ['min', 'max']}],
                        'properties':
                        {'date': {'type': 'string'},
                         'max': {'type': 'integer'},
                         'min': {'type': 'integer'},
                         'text': {'type': 'string'},
                         'value': {'type': 'integer'}},
                        'type': 'object'})]),), ]
