# Generated by Django 2.2.13 on 2020-12-14 12:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import shared.validators


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0040_auto_20201125_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='desired',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON object specifying the desired value:\n        { "text": "" } or { "value": 1 } or { "min": 5, "max": 9 }', null=True, validators=[shared.validators.JSONSchemaValidator(limit_value={'oneOf': [{'required': ['value']}, {'required': ['min', 'max']}, {'required': ['text']}, {'required': ['date']}], 'properties': {'date': {'type': 'string'}, 'max': {'type': 'integer'}, 'min': {'type': 'integer'}, 'text': {'type': 'string'}, 'value': {'type': 'integer'}}, 'type': 'object'})]),
        ),
    ]
