# Generated by Django 2.2.13 on 2021-01-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0043_auto_20201217_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='types',
            field=models.ManyToManyField(blank=True, to='matching.SupporterType'),
        ),
    ]
