# Generated by Django 2.2.13 on 2020-12-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0042_update_question_criteria_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter', name='is_active', field=models.BooleanField(default=True),),
        migrations.AlterField(
            model_name='supporter', name='user_profile', field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporter',
                to='viral.UserProfile'),), ]
