# Generated by Django 2.2.13 on 2021-02-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0043_auto_20210111_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='is_active',
            field=models.BooleanField(default=True, help_text='To filter outdated Criteria of a Supporter'),
        ),
    ]
