# Generated by Django 2.2.13 on 2021-03-12 11:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import shared.validators


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0045_update_question_criteria_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='desired',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON object specifying the desired value:\n        { "text": "" } or { "value": 1 } or { "min": 5, "max": 9 }', null=True, validators=[shared.validators.JSONSchemaValidator(limit_value={'oneOf': [{'required': ['value']}, {'required': ['min', 'max']}, {'required': ['text']}, {'required': ['date']}], 'properties': {'date': {'type': 'string'}, 'max': {'type': 'number'}, 'min': {'type': 'number'}, 'text': {'type': 'string'}, 'value': {'type': 'number'}}, 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='response',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON object specifying the value: { "text": "" } or { "value": 1 } or { "min": 5, "max": 9 }', null=True, validators=[shared.validators.JSONSchemaValidator(limit_value={'oneOf': [{'required': ['text']}, {'required': ['value']}, {'required': ['date']}, {'required': ['min', 'max']}], 'properties': {'date': {'type': 'string'}, 'max': {'type': 'number'}, 'min': {'type': 'number'}, 'text': {'type': 'string'}, 'value': {'type': 'number'}}, 'type': 'object'})]),
        ),
    ]
