# Generated by Django 2.2.13 on 2021-03-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0046_auto_20210312_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestedcta',
            name='entrepreneur_is_interested',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Request Sent'), (2, 'Connected'), (3, 'Past Connection')], default=0, help_text='0 (Initial) 1 (Interested)'),
        ),
        migrations.AlterField(
            model_name='interestedcta',
            name='state_of_interest',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Request Sent'), (2, 'Connected'), (3, 'Past Connection')], default=0, help_text='0 (No connection) 1 (Someone has interest) 2 (Connected) 3 (Disconnected)'),
        ),
        migrations.AlterField(
            model_name='interestedcta',
            name='supporter_is_interested',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Request Sent'), (2, 'Connected'), (3, 'Past Connection')], default=0, help_text='0 (Initial) 1 (Interested)'),
        ),
    ]
