# Generated by Django 2.0.13 on 2020-05-13 19:31
from django.apps import apps
from django.db import migrations
from shared.execute_raw_sql import ExecuteRawSQL

# Specify algorithm version and directory path containing SQL files
algorithm_version = '1.0.9'
algorithm_path = apps.get_app_config(
    'matching').path + '/algorithm/' + algorithm_version

# Instantiate class that will execute SQL files through migration
algorithm = ExecuteRawSQL(algorithm_path, list=['update_active_total_scores_view', 'create_ongoing_calculations'])


class Migration(migrations.Migration):
    dependencies = [
        ('matching', '0048_update_entrepreneur_supporter_view'),
    ]

    operations = [
        migrations.RunPython(algorithm.load_sql),
    ]
