# Generated by Django 2.2.13 on 2021-05-18 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0049_update_active_total_scores_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='criteria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supporteroffering',
            options={},
        ),
    ]
