# Generated by Django 2.2.22 on 2021-08-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0050_auto_20210518_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='entrepreneur_question_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='entrepreneur_question_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='resource_question_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='resource_question_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='short_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='short_name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supporterofferingcategories',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supporterofferingcategories',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supporterofferingtypes',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supporterofferingtypes',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
