# Generated by Django 2.2.22 on 2021-08-13 09:56

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import shared.validators
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0051_auto_20210820_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalResponse',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON object specifying the value: { "text": "" } or { "value": 1 } or { "min": 5, "max": 9 }', null=True, validators=[shared.validators.JSONSchemaValidator(limit_value={'oneOf': [{'required': ['text']}, {'required': ['value']}, {'required': ['date']}, {'required': ['min', 'max']}], 'properties': {'date': {'type': 'string'}, 'max': {'type': 'number'}, 'min': {'type': 'number'}, 'text': {'type': 'string'}, 'value': {'type': 'number'}}, 'type': 'object'})])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(blank=True, db_constraint=False, help_text='Question ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='matching.Question')),
            ],
            options={
                'verbose_name': 'historical response',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
