# Generated by Django 2.2.22 on 2021-09-01 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0021_assessment_from_milestone_planner'),
        ('matching', '0052_historicalresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbundle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grid.Category'),
        ),
        migrations.AddField(
            model_name='questionbundle',
            name='category_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grid.CategoryLevel'),
        ),
    ]
