# Generated by Django 2.2.22 on 2022-01-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0054_update_ongoing_calculations'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='value_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='value_es',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
