# Generated by Django 2.2.27 on 2022-03-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0056_fix_locations_comparion'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportertype',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='supportertype',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='supportertype',
            name='label_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportertype',
            name='label_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportertype',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supportertype',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
