# Generated by Django 2.2.27 on 2022-03-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0057_auto_20220322_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriaweight',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criteriaweight',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
