# Generated by Django 2.2.27 on 2022-04-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0058_auto_20220323_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='entrepreneur_question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='entrepreneur_question_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='entrepreneur_question_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='resource_question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='resource_question_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='resource_question_es',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
