# Generated by Django 2.2.27 on 2022-04-11 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0057_optimize_matching_algorithm'),
        ('matching', '0059_auto_20220406_1110'),
    ]

    operations = [
    ]
