# Generated by Django 2.2.28 on 2022-10-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0060_merge_20220411_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
