# Generated by Django 2.2.28 on 2022-11-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0061_answer_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('order', 'id')},
        ),
    ]
