# Generated by Django 2.2.28 on 2022-11-14 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0087_add_team_member_related_questions'),
        ('matching', '0062_answer_order_model_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresponse',
            name='team_member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='viral.TeamMember'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_team_member_question',
            field=models.BooleanField(default=False, help_text='Set question as targeted for Team Members'),
        ),
        migrations.AddField(
            model_name='questionbundle',
            name='has_team_member_questions',
            field=models.BooleanField(default=False, help_text='Set question bundle as targeted for Team Members'),
        ),
        migrations.AddField(
            model_name='response',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viral.TeamMember'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.QuestionCategory'),
        ),
    ]
