# Generated by Django 2.2.27 on 2023-05-03 10:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import shared.validators


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0063_add_team_member_related_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalresponse',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON object specifying the value: { "text": "" } or { "value": 1 } or { "min": 5, "max": 9 }', null=True, validators=[shared.validators.JSONSchemaValidator(limit_value={'oneOf': [{'required': ['text']}, {'required': ['value']}, {'required': ['date']}, {'required': ['min', 'max']}], 'properties': {'date': {'type': 'string'}, 'max': {'type': 'number'}, 'min': {'type': 'number'}, 'text': {'maxLength': 1500, 'type': 'string'}, 'value': {'type': 'number'}}, 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='response',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON object specifying the value: { "text": "" } or { "value": 1 } or { "min": 5, "max": 9 }', null=True, validators=[shared.validators.JSONSchemaValidator(limit_value={'oneOf': [{'required': ['text']}, {'required': ['value']}, {'required': ['date']}, {'required': ['min', 'max']}], 'properties': {'date': {'type': 'string'}, 'max': {'type': 'number'}, 'min': {'type': 'number'}, 'text': {'maxLength': 1500, 'type': 'string'}, 'value': {'type': 'number'}}, 'type': 'object'})]),
        ),
    ]
