# Generated by Django 2.2.27 on 2023-05-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0064_auto_20230503_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbundle',
            name='capital_explorer',
            field=models.BooleanField(default=False, help_text='Include this question bundle in the Capital Explorer'),
        ),
    ]
