# Generated by Django 2.2.27 on 2023-06-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0065_questionbundle_capital_explorer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='instructions',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='instructions_en',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='instructions_es',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
