# Generated by Django 2.2.27 on 2023-08-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0066_question_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='instructions',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='instructions_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='instructions_es',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
