# Generated by Django 2.2.27 on 2023-08-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0067_answer_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='instructions_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='instructions_es',
            field=models.TextField(blank=True, null=True),
        ),
    ]
